# 选取数据

本节介绍如何从数组对象中选取数据。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

##  位置索引与遍历

前面已经提过，可以使用位置索引与切片的方式来访问数组中的数据。例如，选择数组中的偶数位置的数据：

In [2]:
arr = np.array(range(64))
print(arr[::2])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62]


对于数组对象来说，还可以使用 `for` 循环来遍历其中元素。不过并不建议这么用，须知创建数组的初心就是为了矢量操作。下面为使用`for`语句进行任意维度的数组遍历：

In [3]:
# 一维数组
arr = np.arange(4)
for x in arr:
    print(x)

0
1
2
3


In [20]:
# 二维数组
arr = np.arange(12).reshape((3, 4))
for row in arr:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


也可以使用数组对象的`flat`属性，该属性是数组的元素迭代器，用于迭代数组的每个元素：

In [21]:
# 遍历多维数组每一个元素
arr = np.arange(12).reshape((3, 4))
for element in arr.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11


数组对象还提供有`flatten`方法，该方法会返回一个数组元素的拷贝，也可用于迭代元素：

In [24]:
for element in arr.flatten(order='F'):
    print(element)

0
4
8
1
5
9
2
6
10
3
7
11


## 索引数组

与 Python 的序列对象一样，可以使用索引与切片来访问数组中单个元素或多个元素。然而有时需要访问无规律或任意位置的数据，Numpy 的数组对象还提供更多选取功能，可以使用索引数组---由位置组成的数组---来访问数据。例如在下面示例中，访问数组中`1,2,5,9`对应的数据：

In [6]:
arr = np.arange(64)
print(arr[[1,2,5,9]])

[1 2 5 9]


索引数组是一个整数类型的可迭代对象，位置索引也可以重复：

In [7]:
idx = np.array([1,1,2,3,5,8,13,21,34])
print(arr[idx])

[ 1  1  2  3  5  8 13 21 34]


索引数组还可以是一个多维数组，用来控制返回结果的形状：

In [8]:
idx = np.array([[0, 3], [2, 4]])
print(arr[idx])

[[0 3]
 [2 4]]


对于多维数组，有同样的操作：

In [9]:
arr = np.arange(9).reshape((3, 3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
idx1 = [1, 2]
idx2 = [2, 1]
print(arr[idx1, idx2])

[5 7]


In [11]:
idx1 = np.array([[0, 0], [1, 1]])
idx2 = np.array([[2, 1], [2, 1]])
print(arr[idx1, idx2])

[[2 1]
 [5 4]]


使用 `np.newaxis` 属性，可以将一个数组对象做为新的更高维数组中的一个切片：

In [12]:
arr = np.arange(6).reshape((2, 3))
newarr = arr[:, :, np.newaxis]
print(newarr.shape)
print(newarr)

(2, 3, 1)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]


Numpy 还提供了网格函数`ix_()`，用来生成多维数组的索引未知：

In [13]:
arr = np.arange(12).reshape((3,4))
print(arr[np.ix_([0,2], [1,2,3])])

[[ 1  2  3]
 [ 9 10 11]]


## 布尔数组

除了索引数组，数组对象还可以使用布尔数组来访问其中数据。布尔数组是一个布尔数组成的数组，可以像掩码一样作为索引来使用，其值为True，则对应位置上的值会被保留。布尔数组可以直接创建，或者使用使用比较操作符计算得到。

In [14]:
arr = np.arange(4)
idx = [True, True, False, True]
arr[idx]

array([0, 1, 3])

In [15]:
arr = np.arange(64)
idx = arr % 5 == 0
idx

array([ True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False])

In [16]:
arr[idx]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

可以把这两步写到一起：

In [17]:
arr[(arr > 10) & (arr < 20)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

## `np.where()`函数

Numpy 包还提供了`where()`函数，用来根据根据条件（condition）来选取两个数组的元素，其调用语法为：
```
np.where(condition, [x, y])
```

下面代码演示`np.where()`的使用：

In [18]:
x = np.arange(10)
y = np.arange(10, 0, -1)
x, y

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1]))

In [19]:
# 根据条件挑选二者元素
np.where(x > y, x, y)

array([10,  9,  8,  7,  6,  5,  6,  7,  8,  9])