# 数组查找与排序

对于一个数组，经常需要进行如下操作：
- 查找与搜索
- 排序
- 计数

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## 查找

| 函数          |  说明      |
|:------------------|:-------------|
| `np.argmin(a, axis=None, out=None)`| 沿指定的维度查找最小元素的下标|
| `np.argmax(a, axis=None, out=None)`| 沿指定的维度查找最大元素的下标 |
| `np.argwhere(a)`| 返回满足条件的位置 |
| `np.nonzero(a)`| 查找非零元素的下标 |

### `np.argmin()`

In [2]:
# 查找最小元素的下标：np.argmin
arr = np.array([11, 13, 15, 17, 19, 18, 16, 14, 12, 10])
print(np.argmin(arr))
print(np.argmin(np.array([[2,1,0,3], [1,2,3,4]]), axis=1))

9
[2 0]


### `np.argmax()`

In [3]:
# 查找最大元素的下标：np.argmax
arr = np.array([11, 13, 15, 17, 19, 18, 16, 14, 12, 10])
print(np.argmax(arr))
print(np.argmax(np.array([[2,1,0,3], [1,2,3,4]]), axis=1))

4
[3 3]


### `np.argwhere()`

In [5]:
arr = np.arange(9).reshape(3, 3)
np.argwhere(arr > 4)

array([[1, 2],
       [2, 0],
       [2, 1],
       [2, 2]], dtype=int64)

### `np.nonzero()`

In [6]:
# 查找非零元素下标：np.nonzero
# 返回多个array，每个array是对应维度上的下标
m = np.array([[1,2], [0,1]])
x_idx, y_idx = np.nonzero(m)
x_idx, y_idx

(array([0, 0, 1], dtype=int64), array([0, 1, 1], dtype=int64))

## 排序

- `numpy.sort()`，对数组进行排序，返回排序结果
- `numpy.argsort()`，对数组进行排序，返回排序位置参数

### `numpy.sort()`

`numpy.sort()` 函数返回输入数组的排序副本，其使用语法为：
```
np.sort(a, axis=-1, kind='quicksort', order=None)
```
- 输入
    - `a`: 需要排序的数组
    - `axis`: 数组排序的轴，`axis=0`表示按列排序，`axis=1`表示按行排序
    - `kind='quicksort`
        - 排序（`quicksort`），缺省算法；
        - 归并排序（`mergesort`）；
        - 堆排序（`heapsort`）。
    - `order=None`: 如果数组包含字段，则是要排序的字段
- 输出
    - 返回排序后数组

In [7]:
arr = np.array([11, 13, 15, 17, 19, 18, 16, 14, 12, 10])
np.sort(arr)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### `numpy.argsort()`

`numpy.argsort()` 对数组进行排序，返回在数组中位置索引。

In [8]:
arr = np.array([11, 13, 15, 17, 19, 18, 16, 14, 12, 10])
np.argsort(arr)

array([9, 0, 8, 1, 7, 2, 6, 3, 5, 4], dtype=int64)

In [9]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 计数

- `np.count_nonzero(a, axis=None)`，非零数字计数

In [10]:
print(np.count_nonzero(np.eye(4)))
print(np.count_nonzero([[0, 1, 7, 0, 0], [3, 0, 0, 2, 19]]))

4
5


In [11]:
np.count_nonzero([[0,1,7,0,0],[3,0,0,2,19]], axis=0)

array([1, 1, 1, 1, 1], dtype=int64)

In [12]:
np.count_nonzero([[0,1,7,0,0], [3,0,0,2,19]], axis=1)

array([2, 3], dtype=int64)