# 线性代数基础知识：向量

- 掌握向量的概念
- 掌握向量的计算规则
- 掌握Python中向量的表示方法

## 什么是向量

- 在二维和三维空间中，一个有方向的线段就称为向量

![二维向量](../images/scipy_vector2d.png)

![三维向量](../images/scipy_vector3d.png) 

- n维空间中的向量，可以用一个$n$元组来表示：$(𝑥_1, 𝑥_2, …, 𝑥_𝑛 )$
    - $x_i$表示第$𝑖$个维度上的大小
    - 向量可以理解为$n$维空间中的一个点
    - 它的方向即为原点到这个点连线的方向


## 向量的运算

- 定义了两种二元运算

    - 向量加法：两个向量相加（相同位置相加）得到第三个向量，记为$𝒖+𝒗$
    - 向量数乘：一个数和向量相乘（与每个元素相乘）得到第三个向量，记为$𝑎∙𝒖$


- 运算满足以下公理
    - 向量加法结合律：$𝒖+(𝒗+𝒘)=(𝒖+𝒗)+𝒘$
    - 向量加法交换律：$𝒖+𝒗=𝒗+𝒖$
    - 存在零向量（记为𝟎），使得 $𝒖+𝟎=𝒖$
    - 存在向量加法的逆元素𝒗，使得$𝒖+𝒗=𝟎$
    - 数乘分配律：$𝑎∙(𝒖+𝒗)=𝑎∙𝒖+𝑎∙𝒗， (𝑎+b)∙𝒖=𝑎∙𝒖+𝑏∙𝒖$
    - 乘法相容：$𝑎(𝑏∙𝒖)=(𝑎𝑏)∙𝒖$
    - 数乘存在单位元：$1∙𝒖=𝒖$

## Python中的向量表示

In [1]:
import numpy as np

In [2]:
# 创建一个二维向量
x = np.array([1, 2])
x

array([1, 2])

In [3]:
# 向量加法
x1 = np.array([1, 2])
x2 = np.array([2, 3])
x1 + x2

array([3, 5])

In [4]:
# 向量数乘
x1 = np.array([1, 2])
3 * x1

array([3, 6])

In [5]:
# 创建一个三维向量
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [6]:
# 向量加法
x1 = np.array([1, 2, 3])
x2 = np.array([2, 3, 4])
x1 + x2

array([3, 5, 7])

In [7]:
# 向量数乘
x1 = np.array([1, 2, 3])
3 * x1

array([3, 6, 9])

## 运算公理

In [8]:
u = np.array([1, 2])
v = np.array([3, 4])
w = np.array([5, 6])

In [12]:
# 向量加法结合律
print('u + (v + w) = ', u + (v + w))
print('(u + v) + w = ', (u + v) + w)

u + (v + w) =  [ 9 12]
(u + v) + w =  [ 9 12]


In [13]:
# 向量加法交换律
print('u + v = ', u + v)
print('v + u = ', v + u)

u + v =  [4 6]
v + u =  [4 6]


In [14]:
# 零向量
print('u + 0 =', u + np.zeros_like(u))

u + 0 = [1 2]


In [15]:
# 逆元素
print('u + (-u) =', u + (-u))

u + (-u) = [0 0]


In [16]:
# 数乘分配律：相对于向量加法
print('2 * (u + v) = ', 2 * (u + v))
print('2 * u + 2 * v = ', 2 * u + 2 * v)

2 * (u + v) = [ 8 12]
2 * u + 2 * v = [ 8 12]


In [17]:
# 数乘分配律：相对于域加法
print('(2 + 3) * u = ', (2 + 3) * u)
print('2 * u + 3 * u = ', 2 * u + 3 * u)

(2 + 3) * u =  [ 5 10]
2 * u + 3 * u =  [ 5 10]


In [18]:
# 乘法相容
print('2 * (3 * u) = ', 2 * (3 * u))
print('(2 * 3) * u = ', (2 * 3) * u)

2 * (3 * u) =  [ 6 12]
(2 * 3) * u =  [ 6 12]


In [19]:
# 数乘单位元
print('1 * u =', 1 * u)

1 * u = [1 2]
